export const album = [
  {
    name: 'The Stranger',
    artist: 'Billy Joel',
    image: '/stranger.jpg',
    price: 100,
    profit: 200,
    quantity: 0,
    level: 1,
  },
  {
    name: 'Dark Side of The Moon',
    artist: 'Pink Floyd',
    image: '/moon.png',
    price: 200,
    profit: 450,
    quantity: 0,
    level: 1,
  },
  {
    name: 'News of The World',
    artist: 'Queen',
    image: '/world.jpg',
    price: 500,
    profit: 1250,
    quantity: 0,
    level: 2,
  },
  {
    name: 'Nevermind',
    artist: 'Nirvana',
    image: '/nevermind.jpg',
    price: 1000,
    profit: 1750,
    quantity: 0,
    level: 2,
  },
  {
    name: 'Slippery When Wet',
    artist: 'Bon Jovi',
    image: '/slippery.jpg',
    price: 2000,
    profit: 2500,
    quantity: 0,
    level: 3,
  },
  {
    name: 'Revolver',
    artist: 'The Beatles',
    image: '/revolver.jpg',
    price: 5000,
    profit: 7500,
    quantity: 0,
    level: 3,
  },
  {
    name: 'Goodbye Yellow Brick Road',
    artist: 'Elton John',
    image: '/roaD.jpg',
    price: 15000,
    profit: 21000,
    quantity: 0,
    level: 4,
  },
  {
    name: '52nd Street',
    artist: 'Billy Joel',
    image: '/street.jpg',
    price: 25000,
    profit: 30000,
    quantity: 0,
    level: 4,
  },
  {
    name: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars',
    artist: 'David Bowie',
    image: '/ziggy.jpg',
    price: 40000,
    profit: 55000,
    quantity: 0,
    level: 5,
  },
  {
    name: 'Wish You Were Here',
    artist: 'Pink Floyd',
    image: '/here.png',
    price: 80000,
    profit: 90000,
    quantity: 0,
    level: 6,
  },
  {
    name: 'Thriller',
    artist: 'Michael Jackson',
    image: '/thriller.jpg',
    price: 100000,
    profit: 125000,
    quantity: 0,
    level: 6,
  },
  {
    name: 'Master of Puppets',
    artist: 'Metallica',
    image: '/master.jpg',
    price: 250000,
    profit: 300000,
    quantity: 0,
    level: 7,
  },
  {
    name: 'Stop Making Sense (Live)',
    artist: 'Talking Heads',
    image: '/sense.jpg',
    price: 500000,
    profit: 600000,
    quantity: 0,
    level: 8,
  },
  {
    name: 'Glass Houses',
    artist: 'Billy Joel',
    image: '/glass.jpg',
    price: 1000000,
    profit: 1500000,
    quantity: 0,
    level: 9,
  },
  {
    name: 'Voulez-Vous',
    artist: 'ABBA',
    image: '/vous.jpg',
    price: 1000000,
    profit: 1500000,
    quantity: 0,
    level: 9,
  },
]
